/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clase_18032025;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author claudiacortes
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_t1 = new javax.swing.JLabel();
        lbl_t2 = new javax.swing.JLabel();
        lbl_t3 = new javax.swing.JLabel();
        lbl_t4 = new javax.swing.JLabel();
        jpb_tortuga1 = new javax.swing.JProgressBar();
        jpb_tortuga2 = new javax.swing.JProgressBar();
        jpb_tortuga3 = new javax.swing.JProgressBar();
        jpb_tortuga4 = new javax.swing.JProgressBar();
        btn_inciarCarrera = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_t1.setText("Tortuga 1");

        lbl_t2.setText("Tortuga 2");

        lbl_t3.setText("Tortuga 3");

        lbl_t4.setText("Tortuga 4");

        btn_inciarCarrera.setText("Iniciar carrera");
        btn_inciarCarrera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_inciarCarreraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_t4)
                    .addComponent(lbl_t3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_t2)
                        .addComponent(lbl_t1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpb_tortuga1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpb_tortuga2, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpb_tortuga4, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpb_tortuga3, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_inciarCarrera)
                .addGap(291, 291, 291))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_t1)
                            .addComponent(jpb_tortuga1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addComponent(lbl_t2))
                    .addComponent(jpb_tortuga2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_t3)
                    .addComponent(jpb_tortuga3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_t4)
                    .addComponent(jpb_tortuga4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btn_inciarCarrera)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inciarCarreraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_inciarCarreraMouseClicked
        // Cargar el archivo de texto 
        Tortuga t1 = new Tortuga("Leonardo", 300, 0, "18/3/2025", "18/3/2029");
        Tortuga t2 = new Tortuga("Donatello", 500, 0, "18/3/2025", "18/3/2029");
        Tortuga t3 = new Tortuga("Michelangelo", 100, 0, "18/3/2025", "18/3/2029");
        Tortuga t4 = new Tortuga("Raphael", 60, 0, "18/3/2025", "18/3/2029");
        jpb_tortuga1.setValue(0);
        jpb_tortuga2.setValue(0);
        jpb_tortuga3.setValue(0);
        jpb_tortuga4.setValue(0);
        tortugaGanadora = -1;
        lbl_t1.setText(t1.getNombre());
        lbl_t2.setText(t2.getNombre());
        lbl_t3.setText(t3.getNombre());
        lbl_t4.setText(t4.getNombre());

        // Iniciar simulacion 
        Thread tortuga1 = new Thread(() -> {
            int max = jpb_tortuga1.getMaximum();
            int cont = jpb_tortuga1.getMinimum();
            while (cont < max && tortugaGanadora == -1) {
                int val = jpb_tortuga1.getValue();
                final int progreso = val + 1; // al utilizar la palabra final, NO se puede modificar la variable
                SwingUtilities.invokeLater(() -> {
                    jpb_tortuga1.setValue(progreso);
                });
                cont++;
                try {
                    Thread.sleep(t1.getVelocidad());
                } catch (InterruptedException ex) {
                    System.out.println("Error en la pausa ");
                }
            } // fin del while

            if (cont >= max) {
                //la progress bar esta llena, nuestra tortuga gano
                tortugaGanadora = 1;
                JOptionPane.showMessageDialog(this, "La trtuga ganadora es " + tortugaGanadora);
            }
        });
                //
        Thread tortuga2 = new Thread(() -> {
            int max = jpb_tortuga2.getMaximum();
            int cont = jpb_tortuga2.getMinimum();
            while (cont < max && tortugaGanadora == -1) {
                int val = jpb_tortuga2.getValue();
                final int progreso = val + 1; // al utilizar la palabra final, NO se puede modificar la variable
                SwingUtilities.invokeLater(() -> {
                    jpb_tortuga2.setValue(progreso);
                });
                cont++;
                try {
                    Thread.sleep(t2.getVelocidad());
                } catch (InterruptedException ex) {
                    System.out.println("Error en la pausa ");
                }
            } // fin del while

            if (cont >=  max) {
                //la progress bar esta llena, nuestra tortuga gano
                tortugaGanadora = 2;
                JOptionPane.showMessageDialog(this, "La trtuga ganadora es " + tortugaGanadora);
            }
        });
        

        Thread tortuga3 = new Thread(() -> {
            int max = jpb_tortuga3.getMaximum();
            int cont = jpb_tortuga3.getMinimum();
            while (cont < max && tortugaGanadora == -1) {
                int val = jpb_tortuga3.getValue();
                final int progreso = val + 1; // al utilizar la palabra final, NO se puede modificar la variable
                SwingUtilities.invokeLater(() -> {
                    jpb_tortuga3.setValue(progreso);
                });
                cont++;
                try {
                    Thread.sleep(t3.getVelocidad());
                } catch (InterruptedException ex) {
                    System.out.println("Error en la pausa ");
                }
            } // fin del while

            if (cont >=  max) {
                //la progress bar esta llena, nuestra tortuga gano
                tortugaGanadora = 3;
                JOptionPane.showMessageDialog(this, "La trtuga ganadora es " + tortugaGanadora);
            }
        });

        Thread tortuga4 = new Thread(() -> {
            int max = jpb_tortuga4.getMaximum();
            int cont = jpb_tortuga4.getMinimum();
            while (cont < max && tortugaGanadora == -1) {
                int val = jpb_tortuga4.getValue();
                final int progreso = val + 1; // al utilizar la palabra final, NO se puede modificar la variable
                SwingUtilities.invokeLater(() -> {
                    jpb_tortuga4.setValue(progreso);
                });
                cont++;
                try {
                    Thread.sleep(t4.getVelocidad());
                } catch (InterruptedException ex) {
                    System.out.println("Error en la pausa ");
                }
            } // fin del while

            if (cont >=  max) {
                //la progress bar esta llena, nuestra tortuga gano
                tortugaGanadora = 4;
                JOptionPane.showMessageDialog(this, "La trtuga ganadora es " + tortugaGanadora);
            }
        });
        
        tortuga1.start();
        tortuga2.start();
        tortuga3.start();
        tortuga4.start();
    }//GEN-LAST:event_btn_inciarCarreraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    /*
    1) reiniciar los valores de la carrera
    2) poner logica en una clase separada 
     2.1 o separar la logica en metodos 
    3) utilizar un arraylist para controlar la logica de la carrera 
    */

    /*
    Carrera de tortugas :
    1) cargar de un archivo de texto la información para la carrera 
        -> nombre Tortuga, velocidad tortuga, [carreras, fecha inicio, fecha  fin]
    2) Simulación :  (iniciamos con 4 tortugas)
        2.1 para cada tortuga, debemos tener una progress bar 
        2.2 cadaprogress bar debe avanzar individualmente. 
        2.3 Indicar un ganador. Cuando una tortuga gana, la carrera finaliza automaticamente. 
    3) registro de datos: 
        3.1 Tabla de pos donde vamos guardando a la tortuga ganadora de cada carrera 
        NOTA: no es necesario guardar esta informacion en archivos de texto. 

     */
    private int tortugaGanadora = -1;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_inciarCarrera;
    private javax.swing.JProgressBar jpb_tortuga1;
    private javax.swing.JProgressBar jpb_tortuga2;
    private javax.swing.JProgressBar jpb_tortuga3;
    private javax.swing.JProgressBar jpb_tortuga4;
    private javax.swing.JLabel lbl_t1;
    private javax.swing.JLabel lbl_t2;
    private javax.swing.JLabel lbl_t3;
    private javax.swing.JLabel lbl_t4;
    // End of variables declaration//GEN-END:variables
}
