/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clase_03032025;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author claudiacortes
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        //Modificar el arbol 
        DefaultTreeModel modeloArbol =  (DefaultTreeModel)jt_arbol.getModel();
        
//         Java utiliza DefaultMutableTreeNode tanto para la raiz, como para los nodos y las hojas
        DefaultMutableTreeNode raiz =(DefaultMutableTreeNode) modeloArbol.getRoot();
        raiz.removeAllChildren();

        
        agregarCategorias();
        
       // actualizar el arbol y como se ve 
        modeloArbol.reload();
        DefaultListModel modeloLista = new DefaultListModel();
        jl_personas.setModel(modeloLista);
        
        //Modificar modelo de la tabla 
        DefaultTableModel modeloTabla = (DefaultTableModel)jt_usuarios.getModel();
        modeloTabla.addColumn("Tipo de usuario");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Apellido");
    }
    
    public void agregarCategorias(){
    //Modelo del arbol 
    DefaultTreeModel modelo = (DefaultTreeModel) jt_arbol.getModel();
    // Empezar por la raiz
    // en java, la raiz, las hojas y los nodos todos se pueden utilizar y crear con la clase DefaultMutableTreeNode
    
/*
                            raiz: 
    hijo 1: alumnos        hijo 2: docentes 
        hijo1: juan 
    
    
    */
    DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();
    DefaultMutableTreeNode alumnos = new DefaultMutableTreeNode("Alumnos");
    DefaultMutableTreeNode docentes = new DefaultMutableTreeNode("Docentes");
    
    
//    DefaultMutableTreeNode nuevoAlumno = new DefaultMutableTreeNode("Juan");
//    alumnos.add(nuevoAlumno);
    
    
    raiz.add(alumnos);
    raiz.add(docentes);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_arbol = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();
        jcb_tipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_apellido = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_personas = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        lbl_seleccionadoLista = new javax.swing.JLabel();
        btn_eliminarLista = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_usuarios = new javax.swing.JTable();
        lbl_fila = new javax.swing.JLabel();
        lbl_columna = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_datoSeleccionado = new javax.swing.JLabel();
        btn_eliminarFila = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("JTree");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("animals");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("cat");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("colors");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("blue");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("violet");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("red");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("yellow");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("sports");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("basketball");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("soccer");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("football");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("hockey");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("food");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("hot dogs");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("pizza");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("ravioli");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("bananas");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jt_arbol.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_arbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_arbolMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_arbol);

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido");

        btn_agregar.setText("Agregar");
        btn_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarMouseClicked(evt);
            }
        });

        jcb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alumno", "Docente" }));

        jLabel3.setText("Tipo");

        lbl_nombre.setText("Apellido");

        lbl_apellido.setText("Nombre");

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_agregar)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jcb_tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_apellido, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_eliminar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_nombre)
                                .addGap(257, 257, 257)
                                .addComponent(lbl_apellido)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregar)
                    .addComponent(btn_eliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombre)
                    .addComponent(lbl_apellido))
                .addGap(46, 46, 46))
        );

        jTabbedPane1.addTab("Arbol", jPanel1);

        jl_personas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_personasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jl_personas);

        jLabel4.setText("Usuarios Creados");

        lbl_seleccionadoLista.setText("jLabel5");

        btn_eliminarLista.setText("Eliminar");
        btn_eliminarLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarListaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(lbl_seleccionadoLista))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(btn_eliminarLista)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lbl_seleccionadoLista)
                .addGap(18, 18, 18)
                .addComponent(btn_eliminarLista)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lista", jPanel2);

        jt_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jt_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_usuariosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jt_usuarios);

        lbl_fila.setText("jLabel5");

        lbl_columna.setText("jLabel6");

        jLabel5.setText("Fila");

        jLabel6.setText("Columna");

        lbl_datoSeleccionado.setText("jLabel7");

        btn_eliminarFila.setText("Eliminar");
        btn_eliminarFila.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarFilaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_fila)
                                    .addComponent(lbl_columna)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(lbl_datoSeleccionado)
                        .addGap(160, 160, 160)
                        .addComponent(btn_eliminarFila)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_fila)
                    .addComponent(jLabel5))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_datoSeleccionado)
                            .addComponent(btn_eliminarFila))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_columna))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6)))
                .addGap(79, 79, 79))
        );

        jTabbedPane1.addTab("Tabla", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseClicked
        String nombre = txt_nombre.getText();
        String apellido = txt_apellido.getText();
        /*
         raiz: hijos [alumnos,docentes] 
    0: alumnos         1: docentes 
        */
        DefaultTreeModel modelo = (DefaultTreeModel) jt_arbol.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modelo.getRoot();
        
          //agregar elementos a la lista
        DefaultListModel modeloLista = (DefaultListModel) jl_personas.getModel();
       
        //Agregar elementos a la tabla 
        DefaultTableModel modeloTabla = (DefaultTableModel)jt_usuarios.getModel();
        
        if(jcb_tipo.getSelectedIndex() == 0){
            // agregar alumno
            Alumno nuevoAlumno = new Alumno(nombre,apellido);
            DefaultMutableTreeNode alumnos = (DefaultMutableTreeNode)raiz.getChildAt(0);
            DefaultMutableTreeNode nuevoNodo = new DefaultMutableTreeNode(nuevoAlumno);
            alumnos.add(nuevoNodo);
            modeloLista.addElement(nuevoAlumno);
            
            modeloTabla.addRow(new Object[]{"Alumno",nuevoAlumno.nombre, nuevoAlumno.apellido});
        }else{
            // agregar docente
            Docente nuevoDocente = new Docente(nombre,apellido);
            DefaultMutableTreeNode nuevoNodo = new DefaultMutableTreeNode(nuevoDocente);
            
            DefaultMutableTreeNode docentes = (DefaultMutableTreeNode)raiz.getChildAt(1);
           
            docentes.add(nuevoNodo);
            modeloLista.addElement(nuevoDocente);
            Object[] elementos = {"Docente",nuevoDocente.nombre,nuevoDocente.apellido};
            modeloTabla.addRow(elementos);
        }
        modelo.reload();
        
      
    }//GEN-LAST:event_btn_agregarMouseClicked

    private void jt_arbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_arbolMouseClicked
        Object seleccionado = jt_arbol.getSelectionPath().getLastPathComponent();
        DefaultMutableTreeNode nodoSeleccionado = (DefaultMutableTreeNode) seleccionado;
        Object objetoSleccionado = nodoSeleccionado.getUserObject();
        if (objetoSleccionado instanceof Docente) {
            Docente d = (Docente) objetoSleccionado;
            lbl_apellido.setText(d.apellido);
            lbl_nombre.setText(d.nombre);
        } else if (objetoSleccionado instanceof Alumno) {
            Alumno a = (Alumno) objetoSleccionado;
            lbl_apellido.setText(a.apellido);
            lbl_nombre.setText(a.nombre);
        } else {
            lbl_apellido.setText("DESCONOCIDO");
            lbl_nombre.setText("DESCONOCIDO");
        }
//        raiz>nodo x>hoja 
    }//GEN-LAST:event_jt_arbolMouseClicked

    private void btn_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseClicked
        Object seleccionado = jt_arbol.getSelectionPath().getLastPathComponent();
        DefaultMutableTreeNode nodoSeleccionado = (DefaultMutableTreeNode) seleccionado;
        DefaultMutableTreeNode nodoPadre = (DefaultMutableTreeNode)nodoSeleccionado.getParent();
        if (nodoSeleccionado.isLeaf() && !nodoPadre.isRoot()) {
            nodoSeleccionado.removeFromParent();
            DefaultTreeModel modelo = (DefaultTreeModel) jt_arbol.getModel();
            modelo.reload();
            JOptionPane.showMessageDialog(this, "Elemento eliminado!");
        } else if(nodoSeleccionado.isRoot()) {
            JOptionPane.showMessageDialog(this, "No se puede eliminar la raiz");
        }else{
            JOptionPane.showMessageDialog(this, "No se pueden eliminar los nodos de las categorias");
        }
        
    }//GEN-LAST:event_btn_eliminarMouseClicked

    private void jl_personasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_personasMouseClicked
        // TODO add your handling code here:
            int i = jl_personas.getSelectedIndex();

            DefaultListModel modeloLista = (DefaultListModel) jl_personas.getModel();
            Object objeto = modeloLista.getElementAt(i);
            if(objeto instanceof Alumno){
                System.out.println("Alumno"); 
            }else if(objeto instanceof Docente){
                System.out.println("Maestro");
            }
             lbl_seleccionadoLista.setText(objeto.toString());
    }//GEN-LAST:event_jl_personasMouseClicked

    private void btn_eliminarListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarListaMouseClicked
        int i = jl_personas.getSelectedIndex();
         DefaultListModel modeloLista = (DefaultListModel) jl_personas.getModel();
         modeloLista.remove(i);
          JOptionPane.showMessageDialog(this, "Se elimino el elemento de la lista");
    }//GEN-LAST:event_btn_eliminarListaMouseClicked

    private void jt_usuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_usuariosMouseClicked
        int columna= jt_usuarios.getSelectedColumn();
        int fila = jt_usuarios.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel)jt_usuarios.getModel();
        Object objeto = modelo.getValueAt(fila, columna);
        lbl_fila.setText(fila+"");
        lbl_columna.setText(columna+"");
        lbl_datoSeleccionado.setText(objeto.toString());
    }//GEN-LAST:event_jt_usuariosMouseClicked

    private void btn_eliminarFilaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarFilaMouseClicked
         int fila = jt_usuarios.getSelectedRow();
         DefaultTableModel modelo = (DefaultTableModel)jt_usuarios.getModel();
         modelo.removeRow(fila);
    }//GEN-LAST:event_btn_eliminarFilaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_eliminarFila;
    private javax.swing.JButton btn_eliminarLista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jcb_tipo;
    private javax.swing.JList<String> jl_personas;
    private javax.swing.JTree jt_arbol;
    private javax.swing.JTable jt_usuarios;
    private javax.swing.JLabel lbl_apellido;
    private javax.swing.JLabel lbl_columna;
    private javax.swing.JLabel lbl_datoSeleccionado;
    private javax.swing.JLabel lbl_fila;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_seleccionadoLista;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
