/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clase_24022025;

import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author claudiacortes
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtp_pestanas = new javax.swing.JTabbedPane();
        jp_pestana2 = new javax.swing.JPanel();
        jp_pestana3 = new javax.swing.JPanel();
        jp_pestana4 = new javax.swing.JPanel();
        jp_pestana1 = new javax.swing.JPanel();
        lbl_texto = new javax.swing.JLabel();
        txt_fuente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_foreground = new javax.swing.JButton();
        btn_bg = new javax.swing.JButton();
        jcb_estilo = new javax.swing.JComboBox<>();
        txt_tamano = new javax.swing.JTextField();
        btn_guardarfuente = new javax.swing.JButton();
        btn_guardarTamano = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jp_pestana2Layout = new javax.swing.GroupLayout(jp_pestana2);
        jp_pestana2.setLayout(jp_pestana2Layout);
        jp_pestana2Layout.setHorizontalGroup(
            jp_pestana2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 757, Short.MAX_VALUE)
        );
        jp_pestana2Layout.setVerticalGroup(
            jp_pestana2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        jtp_pestanas.addTab("tab2", jp_pestana2);

        javax.swing.GroupLayout jp_pestana3Layout = new javax.swing.GroupLayout(jp_pestana3);
        jp_pestana3.setLayout(jp_pestana3Layout);
        jp_pestana3Layout.setHorizontalGroup(
            jp_pestana3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 757, Short.MAX_VALUE)
        );
        jp_pestana3Layout.setVerticalGroup(
            jp_pestana3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        jtp_pestanas.addTab("tab3", jp_pestana3);

        javax.swing.GroupLayout jp_pestana4Layout = new javax.swing.GroupLayout(jp_pestana4);
        jp_pestana4.setLayout(jp_pestana4Layout);
        jp_pestana4Layout.setHorizontalGroup(
            jp_pestana4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 757, Short.MAX_VALUE)
        );
        jp_pestana4Layout.setVerticalGroup(
            jp_pestana4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        jtp_pestanas.addTab("tab4", jp_pestana4);

        lbl_texto.setText("Texto");

        jLabel2.setText("Fuente");

        jLabel3.setText("Foreground");

        jLabel4.setText("BackGround");

        jLabel5.setText("Estilo");

        jLabel6.setText("Tamano");

        btn_foreground.setText("select");
        btn_foreground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_foregroundMouseClicked(evt);
            }
        });

        btn_bg.setText("select");

        jcb_estilo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bold", "Italic", "Plain" }));

        btn_guardarfuente.setText("Guardar");

        btn_guardarTamano.setText("Guardar");

        javax.swing.GroupLayout jp_pestana1Layout = new javax.swing.GroupLayout(jp_pestana1);
        jp_pestana1.setLayout(jp_pestana1Layout);
        jp_pestana1Layout.setHorizontalGroup(
            jp_pestana1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_pestana1Layout.createSequentialGroup()
                .addContainerGap(370, Short.MAX_VALUE)
                .addComponent(lbl_texto)
                .addGap(355, 355, 355))
            .addGroup(jp_pestana1Layout.createSequentialGroup()
                .addGroup(jp_pestana1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp_pestana1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_bg, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_pestana1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jp_pestana1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_pestana1Layout.createSequentialGroup()
                                .addGroup(jp_pestana1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(41, 41, 41)
                                .addGroup(jp_pestana1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_fuente)
                                    .addComponent(btn_foreground, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)))
                            .addGroup(jp_pestana1Layout.createSequentialGroup()
                                .addGroup(jp_pestana1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jp_pestana1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcb_estilo, 0, 236, Short.MAX_VALUE)
                                    .addComponent(txt_tamano))))))
                .addGap(18, 18, 18)
                .addGroup(jp_pestana1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_guardarfuente)
                    .addComponent(btn_guardarTamano))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_pestana1Layout.setVerticalGroup(
            jp_pestana1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_pestana1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lbl_texto)
                .addGap(45, 45, 45)
                .addGroup(jp_pestana1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_pestana1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_fuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_guardarfuente))
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(jp_pestana1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btn_foreground))
                .addGap(18, 18, 18)
                .addGroup(jp_pestana1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(btn_bg))
                .addGap(24, 24, 24)
                .addGroup(jp_pestana1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcb_estilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jp_pestana1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_tamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_guardarTamano))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        jtp_pestanas.addTab("Fuente", jp_pestana1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtp_pestanas, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jtp_pestanas, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_foregroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_foregroundMouseClicked
        //JColorChooser -> PascalCase 
       Color seleccionado =  JColorChooser.showDialog(this, "Foreground color", Color.MAGENTA);
        
        lbl_texto.setForeground(seleccionado);
        
        
    }//GEN-LAST:event_btn_foregroundMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bg;
    private javax.swing.JButton btn_foreground;
    private javax.swing.JButton btn_guardarTamano;
    private javax.swing.JButton btn_guardarfuente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> jcb_estilo;
    private javax.swing.JPanel jp_pestana1;
    private javax.swing.JPanel jp_pestana2;
    private javax.swing.JPanel jp_pestana3;
    private javax.swing.JPanel jp_pestana4;
    private javax.swing.JTabbedPane jtp_pestanas;
    private javax.swing.JLabel lbl_texto;
    private javax.swing.JTextField txt_fuente;
    private javax.swing.JTextField txt_tamano;
    // End of variables declaration//GEN-END:variables
}
